"""Adding user shops relationship

Revision ID: daff23253894
Revises: fab2a86c8b63
Create Date: 2020-04-11 08:46:05.071956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "daff23253894"
down_revision = "fab2a86c8b63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
